services:
  postgres:
    image: postgres:17.0
    container_name: postgres
    restart: unless-stopped
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - pgsql_data:/var/lib/postgresql/data
volumes:
  pgsql_data:
