x-healthcheck: &x-healthcheck
  healthcheck:
    test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
    interval: 5s
    timeout: 25s
    retries: 5
  environment:
  - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.3gxk.net,emqx@node2.3gxk.net,emqx@node3.3gxk.net,emqx@node4.3gxk.net,emqx@node5.3gxk.net]"
services:
  emqx1:
    image: emqx/emqx:5.8.0
    container_name: emqx1
    hostname: node1
    environment:
    - "EMQX_NODE_NAME=emqx@node1.3gxk.net"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    volumes:
      - emqx1_data:/opt/emqx/data
      - emqx1_log:/opt/emqx/log
      - emqx1_plugins:/opt/emqx/plugins
    restart: unless-stopped
    <<: *x-healthcheck
    networks:
      emqx-bridge:
        aliases:
        - node1.3gxk.net
  emqx2:
    image: emqx/emqx:5.8.0
    container_name: emqx2
    hostname: node2
    environment:
    - "EMQX_NODE_NAME=emqx@node2.3gxk.net"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    volumes:
      - emqx2_data:/opt/emqx/data
      - emqx2_log:/opt/emqx/log
      - emqx2_plugins:/opt/emqx/plugins
    restart: unless-stopped
    networks:
      emqx-bridge:
        aliases:
        - node2.3gxk.net
  emqx3:
    image: emqx/emqx:5.8.0
    container_name: emqx3
    hostname: node3
    environment:
    - "EMQX_NODE_NAME=emqx@node3.3gxk.net"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    volumes:
      - emqx3_data:/opt/emqx/data
      - emqx3_log:/opt/emqx/log
      - emqx3_plugins:/opt/emqx/plugins
    restart: unless-stopped
    <<: *x-healthcheck
    networks:
      emqx-bridge:
        aliases:
        - node3.3gxk.net
  emqx4:
    image: emqx/emqx:5.8.0
    container_name: emqx4
    hostname: node4
    environment:
    - "EMQX_NODE_NAME=emqx@node4.3gxk.net"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_NODE_ROLE=replicant"
    volumes:
      - emqx4_data:/opt/emqx/data
      - emqx4_log:/opt/emqx/log
      - emqx4_plugins:/opt/emqx/plugins
    restart: unless-stopped
    <<: *x-healthcheck
    networks:
      emqx-bridge:
        aliases:
        - node4.3gxk.net
  emqx5:
    image: emqx/emqx:5.8.0
    container_name: emqx5
    hostname: node5
    environment:
    - "EMQX_NODE_NAME=emqx@node5.3gxk.net"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_NODE_ROLE=replicant"
    volumes:
      - emqx5_data:/opt/emqx/data
      - emqx5_log:/opt/emqx/log
      - emqx5_plugins:/opt/emqx/plugins
    restart: unless-stopped
    <<: *x-healthcheck
    networks:
      emqx-bridge:
        aliases:
        - node5.3gxk.net
networks:
  emqx-bridge:
    driver: bridge
volumes:
  emqx1_data:
  emqx1_log:
  emqx1_plugins:
  emqx2_data:
  emqx2_log:
  emqx2_plugins:
  emqx3_data:
  emqx3_log:
  emqx3_plugins:
  emqx4_data:
  emqx4_log:
  emqx4_plugins:
  emqx5_data:
  emqx5_log:
  emqx5_plugins: