services:
  mysql:
    image: mysql:9.0.1
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: example_password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_conf:/etc/mysql/conf.d
      - mysql_log:/var/log/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
  mysql_conf:
  mysql_log:
