services:
  drone:
    image: drone/drone:2
    container_name: drone
    volumes:
      - /var/lib/drone:/data
    environment:
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GOGS_SERVER=https://git.dev.jidian-iot.cn
      - DRONE_RPC_SECRET=jidian44886
      - DRONE_SERVER_HOST=114.116.119.165:18080
      - DRONE_SERVER_PROTO=http
    ports:
      - "8000:80"
      - "4430:443"
    restart: always

  docker_runner:
    image: drone/drone-runner-docker:1
    container_name: docker_runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=114.116.119.165:18080
      - DRONE_RPC_SECRET=jidian44886
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=runner-docker
    ports:
      - "8001:3000"
    restart: always

  ssh_runner:
    image: drone/drone-runner-ssh
    container_name: ssh_runner
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=114.116.119.165:18080
      - DRONE_RPC_SECRET=jidian44886
    ports:
      - "8002:3000"
    restart: always
