services:
  nats:
    image: nats:2.10.21-alpine
    ports:
      - "4222:4222"
      - "8222:8222"      
    volumes:
      - nats_data:/data
    command:
      - "--name=nats"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"

volumes:
  nats_data: